

cybox_email1_tuple_repr = \
  ( ( '@schemaLocation',
    'http://cybox.mitre.org/cybox_v1          http://cybox.mitre.org/XMLSchema/cybox_core_v1.0(draft).xsd         http://cybox.mitre.org/objects#FileObject         http://cybox.mitre.org/XMLSchema/objects/File/File_Object_1.2.xsd         http://cybox.mitre.org/objects#EmailMessageObject         http://cybox.mitre.org/XMLSchema/objects/Email_Message/Email_Message_Object_1.1.xsd'),
  ('@cybox_major_version', '1'),
  ('@cybox_minor_version', '0(draft)'),
  ( 'Observable',
    ( ( 'Stateful_Measure',
        ( ( 'Object',
            ( ('@id', 'cybox:A1'),
              ('@type', 'Email Message'),
              ( 'Defined_Object',
                ( ('@type', 'EmailMessageObj:EmailMessageObjectType'),
                  ( 'Attachments',
                    ( ( 'File',
                        ( ( '@@reference',
                            'cybox:embedded_reference-6b0a0398-abc8-11e2-8038-000c29279adc'),
                          ('@@embedded_ns', 'FileObj'))),)),
                  ( 'Header',
                    ( ( 'To',
                        ( ( 'Recipient',
                            [ ( ('@category', 'e-mail'),
                                ( 'Address_Value',
                                  ( ('@datatype', 'String'),
                                    ( 'value',
                                      'victim1@target.com')))),
                              ( ('@category', 'e-mail'),
                                ( 'Address_Value',
                                  ( ('@datatype', 'String'),
                                    ( 'value',
                                      'victim2@target.com'))))]),)),
                      ( 'From',
                        ( ('@category', 'e-mail'),
                          ( 'Address_Value',
                            ( ('@datatype', 'String'),
                              ('value', 'attacker@example.com'))))),
                      ( 'Subject',
                        ( ('@datatype', 'String'),
                          ( 'value',
                            'New modifications to the\n                            specification'))))))))),)),)))

cybox_file1_tuple_repr = \
  ( ( 'File_Name',
    ( ('@datatype', 'String'),
      ( 'value',
        'FooBar Specification (critical\n                                revision).doc'))),



  ( 'Hashes',
    ( ( 'Hash',
        ( ( 'Simple_Hash_Value',
            ( ('@datatype', 'hexBinary'),
              ('value', '4EC0027BEF4D7E1786A04D021FA8A67F'))),)),)))


cybox_ur1_tuple_repr = \
  ( ( '@schemaLocation',
    'http://cybox.mitre.org/cybox_v1          http://cybox.mitre.org/XMLSchema/cybox_core_v1.0(draft).xsd         http://cybox.mitre.org/objects#URIObject         http://cybox.mitre.org/XMLSchema/objects/URI/URI_Object_1.1.xsd'),
  ('@cybox_major_version', '1'),
  ('@cybox_minor_version', '0(draft)'),
  ( 'Observable',
    ( ( 'Stateful_Measure',
        ( ( 'Object',
            ( ('@id', 'cybox:A1'),
              ('@type', 'URI'),
              ( 'Defined_Object',
                ( ('@type', 'URIObj:URIObjectType'),
                  ( 'Value',
                    ( ('@condition', 'Equals'),
                      ('@datatype', 'AnyURI'),
                      ('value', 'www.sample1.com/index.html'))))))),)),)))

cybox_email2_tuple_repr = \
  ( ( '@schemaLocation',
    'http://cybox.mitre.org/cybox_v1          http://cybox.mitre.org/XMLSchema/cybox_core_v1.0(draft).xsd         http://cybox.mitre.org/objects#FileObject         http://cybox.mitre.org/XMLSchema/objects/File/File_Object_1.2.xsd         http://cybox.mitre.org/objects#EmailMessageObject         http://cybox.mitre.org/XMLSchema/objects/Email_Message/Email_Message_Object_1.1.xsd'),
  ('@cybox_major_version', '1'),
  ('@cybox_minor_version', '0(draft)'),
  ( 'Observable',
    [ ( ( 'Stateful_Measure',
          ( ( 'Object',
              ( ('@id', 'cybox:A1'),
                ('@type', 'Email Message'),
                ( 'Defined_Object',
                  ( ( '@type',
                      'EmailMessageObj:EmailMessageObjectType'),
                    ( 'Header',
                      ( ( 'To',
                          ( ( 'Recipient',
                              [ ( ('@category', 'e-mail'),
                                  ( 'Address_Value',
                                    ( ( '@datatype',
                                        'String'),
                                      ( 'value',
                                        'victim1@target.com')))),
                                ( ('@category', 'e-mail'),
                                  ( 'Address_Value',
                                    ( ( '@datatype',
                                        'String'),
                                      ( 'value',
                                        'victim2@target.com'))))]),)),
                        ( 'From',
                          ( ('@category', 'e-mail'),
                            ( 'Address_Value',
                              ( ('@datatype', 'String'),
                                ( 'value',
                                  'attacker@example.com'))))),
                        ( 'Subject',
                          ( ('@datatype', 'String'),
                            ( 'value',
                              'New modifications to the\n                            specification'))))))),
                ( 'Related_Objects',
                  ( ( 'Related_Object',
                      ( ('@idref', 'cybox:A2'),
                        ('@relationship', 'Received_From'),
                        ('value', ''))),)))),)),),
      ( ( 'Stateful_Measure',
          ( ( 'Object',
              ( ('@id', 'cybox:A2'),
                ('@type', 'IP Address'),
                ( 'Defined_Object',
                  ( ('@type', 'AddrObj:AddressObjectType'),
                    ('@category', 'ipv4-addr'),
                    ('@is_source', 'true'),
                    ( 'Address_Value',
                      ( ('@datatype', 'String'),
                        ('value', '192.168.1.1'))))))),)),)]))


